server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://rm-bp121b83zt132aok62o.mysql.rds.aliyuncs.com/cxdict?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: cct
    password: cct123!@# 